name:                SpidingShSz
version:             0.1.0.0
github:              "githubuser/SpidingShSz"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/SpidingShSz#readme>

dependencies:
- base >= 4.7 && < 5
- text
- scalpel
- http-client
- bytestring
- tagsoup
- connection
- network
- http-client-tls
- http-types
- case-insensitive
- selda
- selda-sqlite
- regex-base
- regex-posix
- text-icu
- selda-postgresql
- selda-json
- errors
- mtl
- transformers
- transformers-either
- directory
- process
- regex-tdfa
- time
- extra
- unix

library:
  source-dirs: module

executables:
  SpidingShSz:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SpidingShSz

tests:
  SpidingShSz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SpidingShSz
